apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec
spec:
  containers:
    - name: liveness
      image: k8s.gcr.io/busybox
      args:
        - /bin/sh
        - -c
        - echo started;
        - touch /tmp/healthy;
          echo healthy sleep 30;
          rm -rf /tmp/healthy;
          echo unheaalthy;
          sleep 60;
          echo done
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5