apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
bootstrapTokens:
  - groups:
      - system:bootstrappers:kubeadm:default-node-token
    token: abcdef.0123456789abcdef
    ttl: 24h0m0s
    usages:
      - signing
      - authentication
localAPIEndpoint:
  advertiseAddress: 192.168.33.13
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
  imagePullPolicy: Always
  name: master
  taints: null
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: stable
clusterName: kubernetes
apiServer:
  timeoutForControlPlane: 4m0s
  extraArgs:
#    enable-admission-plugins: AlwaysPullImages,DefaultStorageClass
#    audit-log-path: /home/vagrant/audit.log
certificatesDir: /etc/kubernetes/pki
controllerManager:
  extraArgs:
    cluster-cidr: 10.244.0.0/16
#    service-cluster-ip-range: 10.96.0.0/12
    allocate-node-cidrs: "true"
dns: {}
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: registry.k8s.io
networking:
  dnsDomain: cluster.local
#  serviceSubnet: "10.96.0.0/12"
  podSubnet: "10.244.0.0/24"
scheduler: {}
