
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.define "master" do | w |
  w.vm.hostname = "master"
  w.vm.network "private_network", ip: "192.168.33.13"
  w.vm.network "forwarded_port", guest: 6443, host: 6443
  for i in 30000..32767
    w.vm.network "forwarded_port", guest: i, host: i
  end
  w.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
    vb.name = "master"
  end
  w.vm.provision "setup-hosts", :type => "shell", :path => "k8s-setup-master.sh" do |s|
  end
  w.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y git wget vim curl
    modprobe br_netfilter
    echo 1 > /proc/sys/net/ipv4/ip_forward
   SHELL
  end

  config.vm.box = "ubuntu/bionic64"
  config.vm.define "worker-1" do | w |
      w.vm.hostname = "worker-1"
      w.vm.network "private_network", ip: "192.168.33.14"

      w.vm.provider "virtualbox" do |vb|
        vb.memory = "8192"
        vb.cpus = 2
        vb.name = "worker-1"
      end
      w.vm.provision "setup-hosts", :type => "shell", :path => "k8s-setup-master.sh" do |s|
    end
   w.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y git wget vim 
     modprobe br_netfilter
     echo 1 > /proc/sys/net/ipv4/ip_forward
   SHELL
  end

  config.vm.box = "ubuntu/bionic64"
  config.vm.define "worker-2" do | w |
      w.vm.hostname = "worker-2"
      w.vm.network "private_network", ip: "192.168.33.15"

      w.vm.provider "virtualbox" do |vb|
        vb.memory = "8192"
        vb.cpus = 2
        vb.name = "worker-2"
      end
        w.vm.provision "setup-hosts", :type => "shell", :path => "k8s-setup-master.sh" do |s|
  end
   w.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y git wget vim curl
     modprobe br_netfilter
     echo 1 > /proc/sys/net/ipv4/ip_forward
   SHELL
  end

  config.vm.box = "ubuntu/bionic64"
  config.vm.define "worker-3" do | w |
      w.vm.hostname = "worker-3"
      w.vm.network "private_network", ip: "192.168.33.16"

      w.vm.provider "virtualbox" do |vb|
        vb.memory = "8192"
        vb.cpus = 2
        vb.name = "worker-3"
      end
        w.vm.provision "setup-hosts", :type => "shell", :path => "k8s-setup-master.sh" do |s|
  end
   w.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y git wget vim curl
     modprobe br_netfilter
     echo 1 > /proc/sys/net/ipv4/ip_forward
   SHELL
  end

  config.vm.box = "ubuntu/bionic64"
  config.vm.define "worker-4" do | w |
      w.vm.hostname = "worker-4"
      w.vm.network "private_network", ip: "192.168.33.17"

      w.vm.provider "virtualbox" do |vb|
        vb.memory = "8192"
        vb.cpus = 2
        vb.name = "worker-4"
      end
        w.vm.provision "setup-hosts", :type => "shell", :path => "k8s-setup-master.sh" do |s|
  end
   w.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y git wget vim curl
     modprobe br_netfilter
     echo 1 > /proc/sys/net/ipv4/ip_forward
   SHELL
  end
end
